// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VarelaProyectoCloud.Data;

#nullable disable

namespace VarelaProyectoCloud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VarelaProyectoCloud.Models.Espacio", b =>
                {
                    b.Property<int>("espacio_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("espacio_id"));

                    b.Property<int>("capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ubicacion")
                        .HasColumnType("text");

                    b.HasKey("espacio_id");

                    b.ToTable("espacios");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.Evento", b =>
                {
                    b.Property<int>("evento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("evento_id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("lugar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_evento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("evento_id");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.Inscripcion", b =>
                {
                    b.Property<int>("inscripcion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("inscripcion_id"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("evento_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha_inscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("participante_id")
                        .HasColumnType("integer");

                    b.Property<int>("tipo_inscripcion_id")
                        .HasColumnType("integer");

                    b.HasKey("inscripcion_id");

                    b.HasIndex("evento_id");

                    b.HasIndex("participante_id");

                    b.HasIndex("tipo_inscripcion_id");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.Participante", b =>
                {
                    b.Property<int>("participante_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("participante_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institucion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.HasKey("participante_id");

                    b.ToTable("participantes");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.Ponente", b =>
                {
                    b.Property<int>("ponente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ponente_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institucion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.HasKey("ponente_id");

                    b.ToTable("ponentes");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.TipoInscripcion", b =>
                {
                    b.Property<int>("tipo_inscripcion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tipo_inscripcion_id"));

                    b.Property<double>("costo")
                        .HasColumnType("double precision");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("tipo_inscripcion_id");

                    b.ToTable("tipo_inscripcion");
                });

            modelBuilder.Entity("VarelaProyectoCloud.Models.Inscripcion", b =>
                {
                    b.HasOne("VarelaProyectoCloud.Models.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("evento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarelaProyectoCloud.Models.Participante", "participante")
                        .WithMany()
                        .HasForeignKey("participante_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarelaProyectoCloud.Models.TipoInscripcion", "tipo_inscripcion")
                        .WithMany()
                        .HasForeignKey("tipo_inscripcion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("participante");

                    b.Navigation("tipo_inscripcion");
                });
#pragma warning restore 612, 618
        }
    }
}
